### ISSUE TITLE
UPN obrazec se ne pošlje preko e-mail naslova

### ISSUE THREAD

**Issue by mzemljak** [woocart/woocommerce-upn#1]
Prvo - Super zaveda! Vse pohvale! 👍 

UPN obrazec se ob oddanem naročilu brez problemov prikaže.

Imam pa problem, da se UPN obrazec ne pošlje preko e-maila. 
UPN obrazca niti ne vidim, če grem pod naročila.

Je potrebna kakšna posebna nastavitev?

Za pošiljanje računov pa uporabljam [Challan – PDF Invoice & Packing Slip for WooCommerce](https://wordpress.org/plugins/webappick-pdf-invoice-for-woocommerce/)

**Comment by dz0ny** [comment]
Kakor vidim se dodatne informacije vidijo samo če je Pro verzija. Načeloma se lahko UPN pokaze kjerkoli po defaultu pa se samo na teh dveh mestih https://github.com/woocart/woocommerce-upn/blob/main/index.php#L33 (ko zaključi naročilo, in v pregledu naročil), vendar to vidi samo uporabnik.

![image](https://user-images.githubusercontent.com/239513/114831277-7dd68780-9dcd-11eb-89d5-e468e49fc437.png)

**Comment by mzemljak** [comment]
Hvala za odgovor.

Uporabljam PRO verzijo.

Očitno sem narobe razumel kje se UPN obrazec prikazuje. Pri oddanem naročilu in v pregledu naročil uporabnika se UPN obrazec pokaže pravilno. Stvar deluje tako kot je oglaševana. 

Pri e-mailu je pa še vedno težava.
hook **woocommerce_order_details_after_customer_details** je edini, ki ga zaznam da se zgodi ob končanem naročilu.
Sem začetnik v svetu PHP-ja in Wordpress-a, uporabil sem [Query Monitor](https://wordpress.org/plugins/query-monitor/) za pregled hooks-ov.
Hook **woocommerce_email_before_order_table** nisem zasledil ob zaključenem naročilu. 

Bi mogoče bilo treba uporabit kaj takega? 
```
add_filter( 'woocommerce_email_attachments', 'attach_order_notice', 10, 3 );
function attach_order_notice ( $attachments, $email_id, $order ) 
{
    // Only for "New Order" email notification (for admin)
    if( $email_id == 'new_order'  ){
        $attachments[] = get_template_directory() . '/notice.pdf';
        //potrebno dodat k obstoječim attachments
    }
    return $attachments;
}
```
Vendar to je samo za Admin-a, potrebno bi bilo prilagodit, da se pošlje tudi uporabniku.

Z veseljem contributam v repozitorij, vendar bom potreboval malo pomoči.

**Comment by dz0ny** [comment]
Za email se uporablja https://github.com/woocommerce/woocommerce/blob/master/templates/emails/email-order-details.php

- woocommerce_email_before_order_table
- woocommerce_email_after_order_table
- woocommerce_email_order_details

In še par drugih če pogledaš v https://github.com/woocommerce/woocommerce/blob/master/templates/emails/customer-invoice.php

Teh hook nebi smel videti ker se izvejo izven tvojega requesta. Moraš pa hendalt oba primera (ko je htm email in ko je statičen)

Plugin ne dela priponk (ker jih je treba shraniti nekam) ker je to problematično zaradi varnosti, hitrosti. Tako da tista z attachemnti odpade. 

Če želiš prikazat v adminu v manage-orders/edit lahko uporabiš tole https://stackoverflow.com/questions/45615324/add-a-custom-meta-box-on-order-edit-pages-and-display-it-on-the-customer-order-p

**Comment by mzemljak** [comment]
Uporabljam [Flatsome](https://themeforest.net/item/flatsome-multipurpose-responsive-woocommerce-theme/5484319) temo in za email template uporabljam [Kadence WooCommerce Email Designer](https://wordpress.org/plugins/kadence-woocommerce-email-designer/) z [Free Fluid Template](https://www.kadencewp.com/blog/responsive-woocommerce-emails/)

**Comment by dz0ny** [comment]
> Uporabljam [Flatsome](https://themeforest.net/item/flatsome-multipurpose-responsive-woocommerce-theme/5484319) temo in za email template uporabljam [Kadence WooCommerce Email Designer](https://wordpress.org/plugins/kadence-woocommerce-email-designer/) z [Free Fluid Template](https://www.kadencewp.com/blog/responsive-woocommerce-emails/)

Hvala, se bom lokalno poigral in videl kje je problem.

**Comment by mzemljak** [comment]
> > Uporabljam [Flatsome](https://themeforest.net/item/flatsome-multipurpose-responsive-woocommerce-theme/5484319) temo in za email template uporabljam [Kadence WooCommerce Email Designer](https://wordpress.org/plugins/kadence-woocommerce-email-designer/) z [Free Fluid Template](https://www.kadencewp.com/blog/responsive-woocommerce-emails/)
> 
> Hvala, se bom lokalno poigral in videl kje je problem.

Uspelo najti problem?

Uporabljam tudi ta plugin [Advanced Shipment Tracking for WooCommerce](https://wordpress.org/plugins/woo-advanced-shipment-tracking/), ki doda podatke o sledenju "Before order Details". 
![image](https://user-images.githubusercontent.com/41263127/116437518-d0905480-a84d-11eb-8f0e-50b4f72c9c62.png)
Sem tudi to propal spremenit, vendar je rezultat isti. V e-mailu se UPN obrazec ne prikaže.

**Comment by dz0ny** [comment]
> Uporabljam tudi ta plugin [Advanced Shipment Tracking for WooCommerce](https://wordpress.org/plugins/woo-advanced-shipment-tracking/), ki doda podatke o sledenju "Before order Details".

Vidim da uporablja zgoraj omenjen hook https://plugins.trac.wordpress.org/browser/woo-advanced-shipment-tracking/trunk/woocommerce-advanced-shipment-tracking.php#L155

**Comment by dz0ny** [comment]
![image](https://user-images.githubusercontent.com/239513/116694228-4ff16580-a9bf-11eb-81bb-9e971da3fc83.png)

Lahko posim preverič z zadnjo verzijo. Dodal sem da preveri da popravi če je IBAN vnešen z neveljavnimi znaki.

**Comment by mzemljak** [comment]
Preveril in ne deluje.
Izklopil sem vse plugin-e. Pustil samo woocommerce in upn, vendar še vedno ni delovalo.

**Comment by dz0ny** [comment]
Ugh, torej je potrebno dodati attachment hook, in potem v mailu nakazt na sliko v attachmentih.

**Comment by mzemljak** [comment]
Dobro, hvala za pomoč.
Za enkrat bom pustil, da se prikaže samo ob nakupu na spletni strani.
